classdef Eritenel_Parker_09 < Dynamic_Formulation
    %ERITENEL_PARKER_09 Calculates the inertia and stiffness matrices of a
    % multi-stage Drivetrain object according to:
    % [1] T. Eritenel and R. G. Parker, 'Modal properties of three-dimensional
    % helical planetary gears', J. Sound Vib., vol. 325, no. 1-2,
    % pp. 397-420, Aug. 2009. https://doi.org/10.1016/j.jsv.2009.03.002
    % [2] T. Eritenel, 'Three-Dimensional Nonlinear Dynamics and Vibration
    % Reduction of Gear Pairs and Planetary Gears', Ph.D Thesis,
    % Ohio State University, 2011.
    % http://rave.ohiolink.edu/etdc/view?acc_num=osu1298651902
    % [3] T. Eritenel and R. G. Parker, 'An investigation of tooth mesh
    % nonlinearity and partial contact loss in gear pairs using a
    % lumped-parameter model', Mech. Mach. Theory, vol. 56, pp. 28-51,
    % Oct. 2012. https://doi.org/10.1016/j.mechmachtheory.2012.05.002
    %

    methods
        function obj = Eritenel_Parker_09(DT)
            obj@Dynamic_Formulation(DT);

            [obj.M, obj.G] = obj.inertia_matrix();
            obj.K = obj.stiffness_matrix();

        end
    end

    methods(Static)
        function [MM, GG] = stage_inertia_matrix(stage_idx)
        end

        function KK = stage_stiffness_matrix(stage_idx)

            % Eq. (29):
            R = [0, 1, 0, 0, 0, 0; ...
                -1, 0, 0, 0, 0, 0; ...
                0, 0, 1, 0, 0, 0; ...
                0, 0, 0, 0, 1, 0; ...
                0, 0, 0, -1, 0, 0; ...
                0, 0, 0, 0, 0, 1];

            if (strcmp(stage_idx.configuration, 'parallel'))
            elseif (strcmp(stage_idx.configuration, 'planetary'))
                N1 = stage_idx.N_p - 1;

                sun_pla = stage_idx.sub_set('sun_planet');
                pla_rng = stage_idx.sub_set('planet_ring');

                % OBS.: got a negative k_mesh for DTU_10MW planet-ring
                k_sp = sun_pla.k_mesh;
                k_pr = pla_rng.k_mesh;
                % Translational gear mesh stiffness:
                % - odd index: sun-planet;
                % - even index: ring-planet;
                k = repmat([k_sp, k_pr], 1, stage_idx.N_p);

                % Angular position of planets:
                alpha = (0:N1) * (360.0 / stage_idx.N_p);
                % Base helix angle:
                psi = stage_idx.beta_b;
                % Transverse operating pressure angle:
                phi_sp = sun_pla.alpha_wt;
                phi_rp = pla_rng.alpha_wt;

                sum_sin = sum(sind(alpha));
                sum_cos = sum(cosd(alpha));
                sum_sin2 = sum(sind(alpha).^2);
                sum_cos2 = sum(cosd(alpha).^2);
                sum_sc = sum(sind(alpha) .* cosd(alpha));

                %% Sun gear matrices:
                % Eq. (87):
                Upsi_s = @(jdx)([0 0 k(jdx) * r_s * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi(sp)) * sind(psi)) * cosd(psi) 0 0 -k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi(sp)) * sind(psi)) * sind(psi); ...
                    0 0 k(jdx) * r_s ^ 2 * sind(psi) * cosd(psi) 0 0 -k(jdx) * r_s * sind(psi) ^ 2; ...
                    0 0 0 0 k(jdx) * r_s * cosd(psi) ^ 2 0; ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 0 0]);

                % Eq. (88):
                Theta_s = @(jdx)([kappa(jdx) + k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi(sp)) * sind(psi)) ^ 2 k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi(sp)) * sind(psi)) * r_s * sind(psi) 0 0 k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi(sp)) * sind(psi)) * cosd(psi) 0; ...
                    0 k(jdx) * r_s * sind(psi) ^ 2 0 0 k(jdx) * r_s * sind(psi) * cosd(psi) 0; ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 k(jdx) * cosd(psi) ^ 2 0; ...
                    0 0 0 0 0 0]);

                % Eq. (89):
                Xi_s = @(jdx)([kappa(jdx) + k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi(sp)) * sind(psi)) ^ 2 k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi(sp)) * sind(psi)) * r_s * sind(psi) 0 0 k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi(sp)) * sind(psi)) * cosd(psi) 0; ...
                    0 k(jdx) * r_s * sind(psi) ^ 2 0 0 k(jdx) * r_s * sind(psi) * cosd(psi) 0; ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 k(jdx) * cosd(psi) ^ 2 0; ...
                    0 0 0 0 0 0]);

                % Eq. (90):
                Psi_s = @(jdx)([(-L_As - e_s) ^ 2 * k_As + (L_Bs - e_s) ^ 2 * k_Bs + kappa_As + kappa_Bs 0 0 0 -(-L_As - e_s) * k_As - (L_Bs - e_s) * k_Bs 0; ...
                    0 (-L_As - e_s) ^ 2 * k_As + (L_Bs - e_s) ^ 2 * k_Bs + kappa_As + kappa_Bs 0 (-L_As - e_s) * k_As + (L_Bs - e_s) * k_Bs 0 0; ...
                    0 0 kappa_Azs + kappa_Bzs + k(jdx) * r_s ^ 2 * cosd(psi) ^ 2 0 0 -k(jdx) * r_s * sind(psi) * cosd(psi); ...
                    0 0 0 k_As + k_Bs 0 0; ...
                    0 0 0 0 k_As + k_Bs 0; ...
                    0 0 0 0 0 k_Azs + k_Bzs + k(jdx) * sind(psi) ^ 2]);

                % Eq. (91):
                Lambda_s = @(jdx)([k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi_sp) * sind(psi)) * r_p * sind(psi) k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi_sp) * sind(psi)) * ((e_p - c(jdx)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) + kappa(jdx) k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi_sp) * sind(psi)) * r_p * cosd(psi) -k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi_sp) * sind(psi)) * cosd(psi) 0 k(jdx) * ((e_s - c(jdx)) * cosd(psi) - r_s * tand(phi_sp) * sind(psi)) * sind(psi); ...
                    k(jdx) * r_s * r_p * sind(psi) ^ 2 k(jdx) * r_s * sind(psi) * ((e_p - c(jdx)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) k(jdx) * r_s * r_p * sind(psi) * cosd(psi) -k(jdx) * r_s * sind(psi) * cosd(psi) 0 k(jdx) * r_s * sind(psi) ^ 2; ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 0 0; ...
                    k(jdx) * r_p * sind(psi) * cosd(psi) k(jdx) * ((e_p - c(jdx)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) * cosd(psi) k(jdx) * r_p * cosd(psi) ^ 2 -k(jdx) * cosd(psi) ^ 2 0 k(jdx) * sind(psi) * cosd(psi); ...
                    0 0 0 0 0 0]);

                % Eq. (92):
                Gamma_s = @(jdx)([0 0 0 0 0 0; ...
                    0 0 0 0 0 0; ...
                    k(jdx) * r_s * r_p * sind(psi) * cosd(psi) k(jdx) * r_s * cosd(psi) * ((e_p - c(jdx)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) k(jdx) * r_s * r_p * cosd(psi) ^ 2 -k(jdx) * r_s * cosd(psi) ^ 2 0 k(jdx) * r_s * sind(psi) * cosd(psi); ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 0 0; ...
                    -k(jdx) * r_p * sind(psi) ^ 2 -k(jdx) * sind(psi) * ((e_p - c(jdx)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) -k(jdx) * r_p * sind(psi) * cosd(psi) k(jdx) * sind(psi) * cosd(psi) 0 -k(jdx) * sind(psi) ^ 2]);

                % Eq. (28):
                K_s = Upsi_s(1) * sum_sin + R * Upsi_s(1) * R' * sum_cos + Theta_s(1) * sum_sin2 + ...
                    R * Theta_s(1) * R' * sum_cos2 + Xi_s(1) * sum_sc + Psi_s(1);

                % Eq. (31):
                K_si = @(i)(Lambda_s(i) * sind(alpha(i)) + R * Lambda_s(i) * cosd(alpha(i)) + Gamma_s(i));

                %% Ring gear matrices:
                % Eq. (93):
                Upsi_r = [0, 0, k_2 * r_r * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi), 0, 0, k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * sind(psi); ...
                    0, 0, k_2 * r_r * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi), 0, 0, k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * sind(psi); ...
                    0, 0, 0, -k_2 * r_r * cosd(psi) ^ 2 * sind(phi_sp + phi_rp), k_2 * r_r * cosd(psi) ^ 2 * cosd(phi_sp + phi_rp), 0; ...
                    0, 0, 0, 0, 0, -k_2 * sind(psi) * cosd(psi) * sind(phi_sp + phi_rp); ...
                    0, 0, 0, 0, 0, k_2 * cosd(psi) * cosd(phi_sp + phi_rp) * sind(psi); ...
                    0, 0, 0, 0, 0, 0;];

                % Eq. (94):
                Theta_r = [kappa_2 * cosd(phi_sp + phi_rp) ^ 2 + k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) ^ 2, kappa_2 * cosd(phi_sp + phi_rp) * sind(phi_sp + phi_rp) + k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)), 0, -k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp), k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp), 0; ...
                    0, kappa_2 * sind(phi_sp + phi_rp) ^ 2 + k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) ^ 2, 0, -k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp), k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp), 0; ...
                    0, 0, 0, 0, 0, 0; ...
                    0, 0, 0, k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) ^ 2, -k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * cosd(phi_sp + phi_rp), 0; ...
                    0, 0, 0, 0, k_2 * cosd(psi) ^ 2 * cosd(phi_sp + phi_rp) ^ 2, 0; ...
                    0, 0, 0, 0, 0, 0;];

                % Eq. (95):
                Xi_r = [0.2e1 * kappa_2 * cosd(phi_sp + phi_rp) * sind(phi_sp + phi_rp) + 0.2e1 * k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)), k_2 * ((sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp))^2 - (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp))^2) + kappa_2 * (sind(phi_sp + phi_rp)^2 - cosd(phi_sp + phi_rp)^2), 0, k_2 * ((cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp) - (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp)), k_2 * ((sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp) - (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp)), 0; ...
                    0, -0.2e1 * kappa_2 * cosd(phi_sp + phi_rp) * sind(phi_sp + phi_rp) - 0.2e1 * k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)), 0, k_2 * ((sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp) - (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp)), -k_2 * ((cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp) - (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp)), 0; ...
                    0, 0, 0, 0, 0, 0; ...
                    0, 0, 0, -0.2e1 * k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * cosd(phi_sp + phi_rp), k_2 * (-cosd(psi)^2 * sind(phi_sp + phi_rp)^2 + cosd(psi)^2 * cosd(phi_sp + phi_rp)^2), 0; ...
                    0, 0, 0, 0, 0.2e1 * k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * cosd(phi_sp + phi_rp), 0; ...
                    0, 0, 0, 0, 0, 0];

                % Eq. (96):
                Psi_r = [k_Ar * (-L_Ar - e_r) ^ 2 + k_Br * (L_Br - e_r) ^ 2 + kappa_Ar + kappa_Br, 0, 0, 0, -(-L_Ar - e_r) * k_Ar - (L_Br - e_r) * k_Br, 0; ...
                    0, k_Ar * (-L_Ar - e_r) ^ 2 + k_Br * (L_Br - e_r) ^ 2 + kappa_Ar + kappa_Br, 0, (-L_Ar - e_r) * k_Ar + (L_Br - e_r) * k_Br, 0, 0; ...
                    0, 0, kappa_Azr + kappa_Bzr + k_2 * r_r ^ 2 * cosd(psi) ^ 2, 0, 0, k_2 * r_r * cosd(psi) * sind(psi); ...
                    0, (-L_Ar - e_r) * k_Ar + (L_Br - e_r) * k_Br, 0, k_Ar + k_Br, 0, 0; ...
                    -(-L_Ar - e_r) * k_Ar - (L_Br - e_r) * k_Br, 0, 0, 0, k_Ar + k_Br, 0; ...
                    0, 0, k_2 * r_r * cosd(psi) * sind(psi), 0, 0, k_Azr + k_Bzr + k_2 * sind(psi) ^ 2];

                % Eq. (97):
                Lambda_r = [k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) - kappa_2 * cosd(phi_sp + phi_rp) * sind(phi_sp + phi_rp), k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) - kappa_2 * cosd(phi_sp + phi_rp) ^ 2, -k_2 * r_p * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi), -k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp), -k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp), -k_2 * (cosd(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * sind(phi_sp + phi_rp)) * sind(psi); ...
                    k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) - kappa_2 * sind(phi_sp + phi_rp) ^ 2, k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) + kappa_2 * cosd(phi_sp + phi_rp) * sind(phi_sp + phi_rp), -k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * r_p * cosd(psi), -k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp), -k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp), -k_2 * (sind(phi_sp + phi_rp) * ((e_r - c_2) * cosd(psi) - r_r * tand(phi_rp) * sind(psi)) - r_r * sind(psi) * cosd(phi_sp + phi_rp)) * sind(psi); ...
                    0, 0, 0, 0, 0, 0; ...
                    -k_2 * cosd(psi) * sind(phi_sp + phi_rp) * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)), -k_2 * cosd(psi) * sind(phi_sp + phi_rp) * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)), -k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * r_p, k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * cosd(phi_sp + phi_rp), k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) ^ 2, k_2 * sind(psi) * cosd(psi) * sind(phi_sp + phi_rp); ...
                    k_2 * cosd(psi) * cosd(phi_sp + phi_rp) * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)), k_2 * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp), k_2 * cosd(psi) ^ 2 * cosd(phi_sp + phi_rp) * r_p, -k_2 * cosd(psi) ^ 2 * cosd(phi_sp + phi_rp) ^ 2, -k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * cosd(phi_sp + phi_rp), -k_2 * cosd(psi) * cosd(phi_sp + phi_rp) * sind(psi); ...
                    0, 0, 0, 0, 0, 0];

                % Eq. (98):
                Gamma_r = [k_2 * (cosd(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * sind(phi_sp + phi_rp)) * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) - kappa_2 * cosd(phi_sp + phi_rp) * sind(phi_sp + phi_rp) k_2 * (cosd(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * sind(phi_sp + phi_rp)) * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) - kappa_2 * cosd(phi_sp + phi_rp) ^ 2 k_2 * r_p * (cosd(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) -k_2 * (cosd(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp) -k_2 * (cosd(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp) -k_2 * (cosd(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * sind(phi_sp + phi_rp)) * sind(psi); ...
                    k_2 * (sind(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * cosd(phi_sp + phi_rp)) * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) - kappa_2 * sind(phi_sp + phi_rp) ^ 2 k_2 * (sind(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * cosd(phi_sp + phi_rp)) * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) + kappa_2 * cosd(phi_sp + phi_rp) * sind(phi_sp + phi_rp) 0 -k_2 * (sind(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp) -k_2 * (sind(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp) -k_2 * (sind(phi_sp + phi_rp) * ((e(r) - c_2) * cosd(psi) - r(r) * tand(phi_rp) * sind(psi)) - r(r) * sind(psi) * cosd(phi_sp + phi_rp)) * sind(psi); ...
                    k_2 * r(r) * cosd(psi) * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) k_2 * r(r) * cosd(psi) * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) -k_2 * r(r) * r_p * cosd(psi) ^ 2 -k_2 * r(r) * cosd(psi) ^ 2 * cosd(phi_sp + phi_rp) -k_2 * r(r) * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) -k_2 * r(r) * cosd(psi) * sind(psi); ...
                    -k_2 * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp) -k_2 * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * sind(phi_sp + phi_rp) k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * r_p k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * cosd(phi_sp + phi_rp) k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) ^ 2 k_2 * cosd(psi) * sind(phi_sp + phi_rp) * sind(psi); ...
                    k_2 * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp) k_2 * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp) k_2 * cosd(psi) ^ 2 * cosd(phi_sp + phi_rp) * r_p -k_2 * cosd(psi) ^ 2 * cosd(phi_sp + phi_rp) ^ 2 -k_2 * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * cosd(phi_sp + phi_rp) -k_2 * cosd(psi) * cosd(phi_sp + phi_rp) * sind(psi); ...
                    k_2 * sind(psi) * (sind(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) k_2 * sind(psi) * (cosd(phi_sp + phi_rp) * ((e_p - c_2) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) -k_2 * r_p * sind(psi) * cosd(psi) -k_2 * cosd(psi) * cosd(phi_sp + phi_rp) * sind(psi) -k_2 * cosd(psi) * sind(phi_sp + phi_rp) * sind(psi) -k_2 * r(r) * cosd(psi) * sind(psi)];

                % Eq. (28):
                K_r = Upsi_r * sum_sin + R * Upsi_r * R' * sum_cos + Theta_r * sum_sin2 + ...
                    R * Theta_r * R' * sum_cos2 + Xi_r * sum_sc + Psi_r;

                % Eq. (31):
                K_ri = @(i)(Lambda_r(i) * sind(alpha(i)) + R * Lambda_r(i) * cosd(alpha(i)) + Gamma_r(i));

                %% Carrier matrices
                % Eq. (99):
                Upsi_c = [0, 0, -(r_s + r_p) * ((-L_Ap - e_s) * k_Ap + (L_Bp - e_s) * k_Bp), 0, 0, tand(phi_sp) * (r_s + r_p) * (k_Azp + k_Bzp); ...
                    0, 0, -tand(phi_sp) * (r_s + r_p) * ((-L_Ap - e_s) * k_Ap + (L_Bp - e_s) * k_Bp), 0, 0, -(r_s + r_p) * (k_Azp + k_Bzp); ...
                    0, 0, 0, -tand(phi_sp) * (r_s + r_p) * (k_Ap + k_Bp), (r_s + r_p) * (k_Ap + k_Bp), 0; ...
                    0, 0, 0, 0, 0, 0; ...
                    0, 0, 0, 0, 0, 0; ...
                    0, 0, 0, 0, 0, 0];

                % Eq. (100):
                Theta_c = [k_Ap * (-L_Ap - e_s) ^ 2 + k_Bp * (L_Bp - e_s) ^ 2 + (k_Azp + k_Bzp) * tand(phi_sp) ^ 2 * (r_s + r_p) ^ 2 + kappa_Ap + kappa_Bp, -tand(phi_sp) * (r_s + r_p) ^ 2 * (k_Azp + k_Bzp), 0, 0, -(-L_Ap - e_s) * k_Ap - (L_Bp - e_s) * k_Bp, 0; ...
                    0, k_Ap * (-L_Ap - e_s) ^ 2 + k_Bp * (L_Bp - e_s) ^ 2 + (k_Azp + k_Bzp) * (r_s + r_p) ^ 2 + kappa_Ap + kappa_Bp, 0, (-L_Ap - e_s) * k_Ap + (L_Bp - e_s) * k_Bp, 0, 0; ...
                    0, 0, 0, 0, 0, 0; ...
                    0, 0, 0, k_Ap + k_Bp, 0, 0; ...
                    0, 0, 0, 0, k_Ap + k_Bp, 0; ...
                    0, 0, 0, 0, 0, 0];

                % Eq. (101):
                Xi_c = [-0.2e1 * tand(phi_sp) * (r_s + r_p) ^ 2 * (k_Azp + k_Bzp), (-tand(phi_sp)^2 * (r_s + r_p)^2 + (r_s + r_p)^2) * (k_Azp + k_Bzp), 0, 0, 0, 0; ...
                    0, 0.2e1 * tand(phi_sp) * (r_s + r_p) ^ 2 * (k_Azp + k_Bzp), 0, 0, 0, 0; ...
                    0, 0, 0, 0, 0, 0; ...
                    0, 0, 0, 0, 0, 0; ...
                    0, 0, 0, 0, 0, 0; ...
                    0, 0, 0, 0, 0, 0];

                % Eq. (102):
                Psi_c = [(-L_Ac - e_c) ^ 2 * k_Ac + (L_Bc - e_c) ^ 2 * k_Bc + kappa_Ac + kappa_Bc, 0, 0, 0, -(-L_Ac - e_c) * k_Ac - (L_Bc - e_c) * k_Bc, 0; ...
                    0, (-L_Ac - e_c) ^ 2 * k_Ac + (L_Bc - e_c) ^ 2 * k_Bc + kappa_Ac + kappa_Bc, 0, (-L_Ac - e_c) * k_Ac + (L_Bc - e_c) * k_Bc, 0, 0; ...
                    0, 0, kappa(Az, c) + kappa(Bz, c) + kappa_Azp + kappa_Bzp + (tand(phi_sp)^2 * (r_s + r_p)^2 + (r_s + r_p)^2) * (k_Ap + k_Bp), 0, 0, 0; ...
                    0, 0, 0, k_Ac + k_Bc, 0, 0; ...
                    0, 0, 0, 0, k_Ac + k_Bc, 0; ...
                    0, 0, 0, 0, 0, k_Azc + k_Bzc + k_Azp + k_Bzp];

                % Eq. (103):
                Lambda_c = [0, (-L_Ap - e_s) * (-L_Ap - e_p) * k_Ap + (L_Bp - e_s) * (L_Bp - e_p) * k_Bp + kappa_Ap + kappa_Bp, 0, (-L_Ap - e_s) * k_Ap + (L_Bp - e_s) * k_Bp, 0, -tand(phi_sp) * (r_s + r_p) * (k_Azp + k_Bzp); ...
                    -(-L_Ap - e_s) * (-L_Ap - e_p) * k_Ap - (L_Bp - e_s) * (L_Bp - e_p) * k_Bp - kappa_Ap - kappa_Bp, 0, 0, 0, (-L_Ap - e_s) * k_Ap + (L_Bp - e_s) * k_Bp, (r_s + r_p) * (k_Azp + k_Bzp); ...
                    tand(phi_sp) * (r_s + r_p) * ((-L_Ap - e_p) * k_Ap + (L_Bp - e_p) * k_Bp), -(r_s + r_p) * ((-L_Ap - e_p) * k_Ap + (L_Bp - e_p) * k_Bp), -kappa_Azp - kappa_Bzp, -(r_s + r_p) * (k_Ap + k_Bp), -tand(phi_sp) * (r_s + r_p) * (k_Ap + k_Bp), 0; ...
                    -(-L_Ap - e_p) * k_Ap - (L_Bp - e_p) * k_Bp, 0, 0, 0, k_Ap + k_Bp, 0; ...
                    0, -(-L_Ap - e_p) * k_Ap - (L_Bp - e_p) * k_Bp, 0, -k_Ap - k_Bp, 0, 0; ...
                    0, 0, 0, 0, 0, -k_Azp - k_Bzp];

                % Eq. (104):
                Gamma_c = [0 0 0 0 0 0; ...
                    0 0 0 0 0 0; ...
                    tand(phi_sp) * (r_s + r_p) * ((-L_Ap - e_p) * k_Ap + (L_Bp - e_p) * k_Bp) -(r_s + r_p) * ((-L_Ap - e_p) * k_Ap + (L_Bp - e_p) * k_Bp) -kappa_Azp - kappa_Bzp -(r_s + r_p) * (k_Ap + k_Bp) tand(phi_sp) * (r_s + r_p) * (k_Ap + k_Bp) 0; ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 0 0; ...
                    0 0 0 0 0 -k_Azp - k_Bzp];

                % Eq. (28):
                K_c = Upsi_c * sum_sin + R * Upsi_c * R' * sum_cos + Theta_c * sum_sin2 + ...
                    R * Theta_c * R' * sum_cos2 + Xi_c * sum_sc + Psi_c;

                % Eq. (31):
                K_ci = @(i)(Lambda_c(i) * sind(alpha(i)) + R * Lambda_c(i) * cosd(alpha(i)) + Gamma_c(i));

                %% Planet matrices:
                % Eq. (105): relates to planet i. The quantity 2*jdx - 1
                % indicates the sun–planet mesh, and 2*jdx indicates the
                % ring-planet mesh:
                Ki = @(jdx)([k(2 * jdx - 1) * r_p ^ 2 * sind(psi) ^ 2 + k(2 * jdx) * (sind(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) ^ 2 + kappa(2 * jdx) * sind(phi_sp + phi_rp) ^ 2 + k_Ap * (-L_Ap - e_p) ^ 2 + k_Bp * (L_Bp - e_p) ^ 2 + kappa_Ap + kappa_Bp k(2 * jdx - 1) * ((e_p - c(2 * jdx - 1)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) * r_p * sind(psi) + k(2 * jdx) * (sind(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) * (cosd(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) - kappa(2 * jdx) * cosd(phi_sp + phi_rp) * sind(phi_sp + phi_rp) (k(2 * jdx - 1) * r_p * sind(psi) - k(2 * jdx) * (sind(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp))) * r_p * cosd(psi) -k(2 * jdx - 1) * r_p * sind(psi) * cosd(psi) - k(2 * jdx) * cosd(psi) * cosd(phi_sp + phi_rp) * (sind(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) -k(2 * jdx) * cosd(psi) * sind(phi_sp + phi_rp) * (sind(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)) - (-L_Ap - e_p) * k_Ap - (L_Bp - e_p) * k_Bp k(2 * jdx - 1) * r_p * sind(psi) ^ 2 - k(2 * jdx) * sind(psi) * (sind(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * cosd(phi_sp + phi_rp)); ...
                    0 k(2 * jdx - 1) * ((e_p - c(2 * jdx - 1)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) ^ 2 + k(2 * jdx) * (cosd(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) ^ 2 + kappa(2 * jdx - 1) + kappa(2 * jdx) * cosd(phi_sp + phi_rp) ^ 2 + k_Ap * (-L_Ap - e_p) ^ 2 + k_Bp * (L_Bp - e_p) ^ 2 + kappa_Ap + kappa_Bp (k(2 * jdx - 1) * ((e_p - c(2 * jdx - 1)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) - k(2 * jdx) * (cosd(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp))) * r_p * cosd(psi) -k(2 * jdx - 1) * ((e_p - c(2 * jdx - 1)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) * cosd(psi) - k(2 * jdx) * (cosd(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) * cosd(psi) * cosd(phi_sp + phi_rp) + (-L_Ap - e_p) * k_Ap + (L_Bp - e_p) * k_Bp -k(2 * jdx) * cosd(psi) * sind(phi_sp + phi_rp) * (cosd(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) k(2 * jdx - 1) * ((e_p - c(2 * jdx - 1)) * cosd(psi) + r_p * tand(phi_sp) * sind(psi)) * sind(psi) - k(2 * jdx) * (cosd(phi_sp + phi_rp) * ((e_p - c(2 * jdx)) * cosd(psi) - r_p * tand(phi_rp) * sind(psi)) + r_p * sind(psi) * sind(phi_sp + phi_rp)) * sind(psi); ...
                    0 0 (k(2 * jdx - 1) + k(2 * jdx)) * r_p ^ 2 * cosd(psi) ^ 2 + kappa_Azp + kappa_Bzp (k(2 * jdx) * cosd(psi) * cosd(phi_sp + phi_rp) - k(2 * jdx - 1) * cosd(psi)) * r_p * cosd(psi) k(2 * jdx) * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * r_p (k(2 * jdx - 1) + k(2 * jdx)) * r_p * sind(psi) * cosd(psi); ...
                    0 0 0 k(2 * jdx - 1) * cosd(psi) ^ 2 + k(2 * jdx) * cosd(psi) ^ 2 * cosd(phi_sp + phi_rp) ^ 2 + k_Ap + k_Bp k(2 * jdx) * cosd(psi) ^ 2 * sind(phi_sp + phi_rp) * cosd(phi_sp + phi_rp) -(k(2 * jdx - 1) * cosd(psi) - k(2 * jdx) * cosd(psi) * cosd(phi_sp + phi_rp)) * sind(psi); ...
                    0 0 0 0 cosd(psi) ^ 2 * sind(phi_sp + phi_rp) ^ 2 * k(2 * jdx) + K_Bp + k_Ap k(2 * jdx) * sind(psi) * cosd(psi) * sind(phi_sp + phi_rp); ...
                    0 0 0 0 0 (k(2 * jdx - 1) + k(2 * jdx)) * sind(psi) ^ 2 + k_Azp + k_Bzp]);

                %% Assembling overall matrix:
                np = 6 * stage_idx.N_p;
                K11 = blkdiag(K_s, K_r, K_c);

                K_s_row = zeros(6, np);
                K_r_row = K_s_row;
                K_c_row = K_s_row;
                K_cell = cell(1, stage_idx.N_p);

                for idx = 1:stage_idx.N_p
                    rng = (-5:0) + 6 * idx;
                    K_s_row(:, rng) = K_si(idx);
                    K_r_row(:, rng) = K_ri(idx);
                    K_c_row(:, rng) = K_ci(idx);
                    
                    K_cell{idx} = Ki(idx);
                end

                K12 = [K_s_row; ...
                       K_r_row; ...
                       K_c_row];

                K22 = blkdiag(K_cell{:});

                KK = [K11,  K12; ...
                      K12', K22];

            end

        end


    end


end
