function update_subvar(obj)
    fprintf(new_ID, "!file.version=3.4! Removing this line will make the file unreadable\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "!**********************************************************************\n");
    fprintf(new_ID, "! SubVars\n");
    fprintf(new_ID, "!**********************************************************************\n");
    fprintf(new_ID, "subvar($_rated_speed, str= '%e rpm')                                                        ! $_rated_speed\n", obj.n_rotor);
    fprintf(new_ID, "subvar($_damping_coeff, str= '10e-6 m')                                                       ! $_damping_coeff\n");
    fprintf(new_ID, "subvar($_addendum_coeff, str= '1.0')                                                          ! $_addendum_coeff\n");
    fprintf(new_ID, "subvar($_dedendum_coeff, str= '1.25')                                                         ! $_dedendum_coeff\n");
    fprintf(new_ID, "subvar($_regularization_vel, str= '1.0e-3')                                                   ! $_regularization_vel\n");
    fprintf(new_ID, "subvar($_tooth_damping, str= '5.0e8 N/(m/s)')                                                 ! $_tooth_damping\n");
    fprintf(new_ID, "subvar($_tooth_stiff_ratio, str= '0.8')                                                       ! $_tooth_stiff_ratio\n");
    fprintf(new_ID, "subvar($_height, str= '1.75 m')                                                               ! $_height\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_material                 )                           ! $SVG_material\n");
    fprintf(new_ID, "   subvar($_E, str= '%e Pa', desc (   1) = 'Young\'s modulus')                           ! $SVG_material.$_E\n", Material.E);
    fprintf(new_ID, "   subvar($_nu, str= '%e', desc (   1) = 'Poisson\'s ratio')                                 ! $SVG_material.$_nu\n", Material.nu);
    fprintf(new_ID, "   subvar($_rho, str= '%e kg/m^3', desc (   1) = 'Density')                               ! $SVG_material.$_rho\n", Material.rho);
    fprintf(new_ID, "subvargroup.end (                   $SVG_material                 )                           ! $SVG_material\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_bed_plate                )                           ! $SVG_bed_plate\n");
    fprintf(new_ID, "   subvar($_length, str= 'anint($SVG_bed_plate.$_x_gen) m')                                   ! $SVG_bed_plate.$_length\n");
    fprintf(new_ID, "   subvar($_width, str= '$SVG_bed_plate.$_length')                                            ! $SVG_bed_plate.$_width\n");
    fprintf(new_ID, "   subvar($_thickness, str= '0.5 m')                                                          ! $SVG_bed_plate.$_thickness\n");
    fprintf(new_ID, "   subvar($_x_gen, str= '$SVG_stage_03.$SVG_wheel.$SVG_C.$_x_GB + $SVG_stage_03.$SVG_shaft.$_length') ! $SVG_bed_plate.$_x_gen\n");
    fprintf(new_ID, "subvargroup.end (                   $SVG_bed_plate                )                           ! $SVG_bed_plate\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_main_shaft               )                           ! $SVG_main_shaft\n");
    fprintf(new_ID, "   subvar($_diameter, str= '%e mm')                                                        ! $SVG_main_shaft.$_diameter\n", obj.main_shaft.d);
    fprintf(new_ID, "   subvar($_length, str= '%e mm')                                                         ! $SVG_main_shaft.$_length\n", obj.main_shaft.L);
    fprintf(new_ID, "subvargroup.end (                   $SVG_main_shaft               )                           ! $SVG_main_shaft\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_GB_frame                 )                           ! $SVG_GB_frame\n");
    fprintf(new_ID, "   subvar($_length, str= '3.5 m')                                                             ! $SVG_GB_frame.$_length\n");
    fprintf(new_ID, "   subvar($_width, str= '2.0*$_height')                                                       ! $SVG_GB_frame.$_width\n");
    fprintf(new_ID, "   subvar($_x, str= '($SVG_main_shaft.$_length*7/4 - $SVG_bed_plate.$_length + $SVG_GB_frame.$_length)/2.0') ! $SVG_GB_frame.$_x\n");
    fprintf(new_ID, "subvargroup.end (                   $SVG_GB_frame                 )                           ! $SVG_GB_frame\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_INP_A                    )                           ! $SVG_INP_A\n");
    fprintf(new_ID, "   subvar($_x, str= '$SVG_main_shaft.$_length/6.0')                                           ! $SVG_INP_A.$_x\n");
    fprintf(new_ID, "   subvar($_K_x, str= '0.0 N/m')                                                              ! $SVG_INP_A.$_K_x\n");
    fprintf(new_ID, "   subvar($_K_y, str= '%e N/m')                                                          ! $SVG_INP_A.$_K_y\n");
    fprintf(new_ID, "   subvar($_K_z, str= '$SVG_INP_A.$_K_y')                                                     ! $SVG_INP_A.$_K_z\n");
    fprintf(new_ID, "   subvar($_K_alpha, str= '0.0 Nm/rad')                                                       ! $SVG_INP_A.$_K_alpha\n");
    fprintf(new_ID, "   subvar($_K_beta, str= '%e Nm/rad')                                                      ! $SVG_INP_A.$_K_beta\n");
    fprintf(new_ID, "   subvar($_K_gamma, str= '$SVG_INP_A.$_K_beta')                                              ! $SVG_INP_A.$_K_gamma\n");
    fprintf(new_ID, "   subvar($_D_x, str= '0.0 N/(m/s)')                                                          ! $SVG_INP_A.$_D_x\n");
    fprintf(new_ID, "subvargroup.end (                   $SVG_INP_A                    )                           ! $SVG_INP_A\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_INP_B                    )                           ! $SVG_INP_B\n");
    fprintf(new_ID, "   subvar($_x, str= '$SVG_main_shaft.$_length*3.0/4.0')                                       ! $SVG_INP_B.$_x\n");
    fprintf(new_ID, "   subvar($_K_x, str= '%e N/m')                                                           ! $SVG_INP_B.$_K_x\n");
    fprintf(new_ID, "   subvar($_K_y, str= '%e N/m')                                                          ! $SVG_INP_B.$_K_y\n");
    fprintf(new_ID, "   subvar($_K_z, str= '$SVG_INP_B.$_K_y')                                                     ! $SVG_INP_B.$_K_z\n");
    fprintf(new_ID, "   subvar($_K_alpha, str= '0.0 Nm/rad')                                                       ! $SVG_INP_B.$_K_alpha\n");
    fprintf(new_ID, "   subvar($_K_beta, str= '0.0 Nm/rad')                                                        ! $SVG_INP_B.$_K_beta\n");
    fprintf(new_ID, "   subvar($_K_gamma, str= '$SVG_INP_B.$_K_beta')                                              ! $SVG_INP_B.$_K_gamma\n");
    fprintf(new_ID, "subvargroup.end (                   $SVG_INP_B                    )                           ! $SVG_INP_B\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_stage_01                 )                           ! $SVG_stage_01\n");
    fprintf(new_ID, "   subvar($_normal_module, str= '%e mm')                                                    ! $SVG_stage_01.$_normal_module\n");
    fprintf(new_ID, "   subvar($_face_width, str= '%e mm')                                                      ! $SVG_stage_01.$_face_width\n");
    fprintf(new_ID, "   subvar($_center_distance, str= '%e mm')                                                 ! $SVG_stage_01.$_center_distance\n");
    fprintf(new_ID, "   subvar($_pressure_angle, str= '20.0 deg')                                                  ! $SVG_stage_01.$_pressure_angle\n");
    fprintf(new_ID, "   subvar($_helix_angle, str= '0.0 deg')                                                      ! $SVG_stage_01.$_helix_angle\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_sun                      )                           ! $SVG_stage_01.$SVG_sun\n");
    fprintf(new_ID, "      subvar($_num_teeth, str= '19')                                                          ! $SVG_stage_01.$SVG_sun.$_num_teeth\n");
    fprintf(new_ID, "      subvar($_prof_shift_coeff, str= '0.617')                                                ! $SVG_stage_01.$SVG_sun.$_prof_shift_coeff\n");
    fprintf(new_ID, "      subvar($_diam_bore, str= '%e mm')                                                    ! $SVG_stage_01.$SVG_sun.$_diam_bore\n");
    fprintf(new_ID, "      subvar($_angle, str= '11.5*(180deg)/$SVG_stage_01.$SVG_sun.$_num_teeth')                ! $SVG_stage_01.$SVG_sun.$_angle\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_sun                      )                           ! $SVG_stage_01.$SVG_sun\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_planet                   )                           ! $SVG_stage_01.$SVG_planet\n");
    fprintf(new_ID, "      subvar($_num_teeth, str= '17')                                                          ! $SVG_stage_01.$SVG_planet.$_num_teeth\n");
    fprintf(new_ID, "      subvar($_prof_shift_coeff, str= '0.802')                                                ! $SVG_stage_01.$SVG_planet.$_prof_shift_coeff\n");
    fprintf(new_ID, "      subvar($_diam_bore, str= '%e mm')                                                    ! $SVG_stage_01.$SVG_planet.$_diam_bore\n");
    fprintf(new_ID, "      subvar($_pin_width, str= '1.4*$SVG_stage_01.$_face_width')                              ! $SVG_stage_01.$SVG_planet.$_pin_width\n");
    fprintf(new_ID, "      subvar($_angle, str= '5.25*(360deg)/$SVG_stage_01.$SVG_planet.$_num_teeth')             ! $SVG_stage_01.$SVG_planet.$_angle\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_A                        )                           ! $SVG_stage_01.$SVG_planet.$SVG_A\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_01.$SVG_carrier.$_width/2.0')                           ! $SVG_stage_01.$SVG_planet.$SVG_A.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_01.$SVG_planet.$SVG_A.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_01.$SVG_planet.$SVG_A.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '%e N/m')                                                      ! $SVG_stage_01.$SVG_planet.$SVG_A.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_01.$SVG_planet.$SVG_A.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '%e Nm/rad')                                                ! $SVG_stage_01.$SVG_planet.$SVG_A.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '%e Nm/rad')                                               ! $SVG_stage_01.$SVG_planet.$SVG_A.$_K_gamma\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_A                        )                           ! $SVG_stage_01.$SVG_planet.$SVG_A\n");
    fprintf(new_ID, "      subvargroup.desc (   1 ,      $SVG_A                        ) = 'PL_A, PL_B, and PL_C'  ! Description\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_planet                   )                           ! $SVG_stage_01.$SVG_planet\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_ring                     )                           ! $SVG_stage_01.$SVG_ring\n");
    fprintf(new_ID, "      subvar($_num_teeth, str= '56')                                                          ! $SVG_stage_01.$SVG_ring.$_num_teeth\n");
    fprintf(new_ID, "      subvar($_prof_shift_coeff, str= '-0.501')                                               ! $SVG_stage_01.$SVG_ring.$_prof_shift_coeff\n");
    fprintf(new_ID, "      subvar($_diam_bore, str= '%e mm')                                                    ! $SVG_stage_01.$SVG_ring.$_diam_bore\n");
    fprintf(new_ID, "      subvar($_angle, str= '27*(180 deg)/$SVG_stage_01.$SVG_ring.$_num_teeth')                ! $SVG_stage_01.$SVG_ring.$_angle\n");
    fprintf(new_ID, "      subvar($_x, str= '$SVG_main_shaft.$_length + $SVG_stage_01.$SVG_carrier.$_width/2.0')   ! $SVG_stage_01.$SVG_ring.$_x\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_ring                     )                           ! $SVG_stage_01.$SVG_ring\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_carrier                  )                           ! $SVG_stage_01.$SVG_carrier\n");
    fprintf(new_ID, "      subvar($_diameter_in, str= '1.4*$SVG_stage_01.$_center_distance	')                      ! $SVG_stage_01.$SVG_carrier.$_diameter_in\n");
    fprintf(new_ID, "      subvar($_diameter_out, str= '2.6*$SVG_stage_01.$_center_distance	')                     ! $SVG_stage_01.$SVG_carrier.$_diameter_out\n");
    fprintf(new_ID, "      subvar($_width, str= '1.2*$SVG_stage_01.$_face_width')                                  ! $SVG_stage_01.$SVG_carrier.$_width\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_A                        )                           ! $SVG_stage_01.$SVG_carrier.$SVG_A\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_01.$SVG_carrier.$_width/2.0')                           ! $SVG_stage_01.$SVG_carrier.$SVG_A.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_01.$SVG_carrier.$SVG_A.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_01.$SVG_carrier.$SVG_A.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '%e N/m')                                                      ! $SVG_stage_01.$SVG_carrier.$SVG_A.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_01.$SVG_carrier.$SVG_A.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '%e Nm/rad')                                                ! $SVG_stage_01.$SVG_carrier.$SVG_A.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '%e Nm/rad')                                               ! $SVG_stage_01.$SVG_carrier.$SVG_A.$_K_gamma\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_A                        )                           ! $SVG_stage_01.$SVG_carrier.$SVG_A\n");
    fprintf(new_ID, "      subvargroup.desc (   1 ,      $SVG_A                        ) = 'PLC_A'                 ! Description\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_B                        )                           ! $SVG_stage_01.$SVG_carrier.$SVG_B\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_main_shaft.$_length+$SVG_stage_01.$SVG_carrier.$_width')      ! $SVG_stage_01.$SVG_carrier.$SVG_B.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_01.$SVG_carrier.$SVG_B.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '$SVG_stage_01.$SVG_carrier.$SVG_A.$_K_y')                        ! $SVG_stage_01.$SVG_carrier.$SVG_B.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '$SVG_stage_01.$SVG_carrier.$SVG_A.$_K_z')                        ! $SVG_stage_01.$SVG_carrier.$SVG_B.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_01.$SVG_carrier.$SVG_B.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '$SVG_stage_01.$SVG_carrier.$SVG_A.$_K_beta')                  ! $SVG_stage_01.$SVG_carrier.$SVG_B.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '$SVG_stage_01.$SVG_carrier.$SVG_A.$_K_gamma')                ! $SVG_stage_01.$SVG_carrier.$SVG_B.$_K_gamma\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_B                        )                           ! $SVG_stage_01.$SVG_carrier.$SVG_B\n");
    fprintf(new_ID, "      subvargroup.desc (   1 ,      $SVG_B                        ) = 'PLC_B'                 ! Description\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_carrier                  )                           ! $SVG_stage_01.$SVG_carrier\n");
    fprintf(new_ID, "   subvargroup.desc (     1 ,       $SVG_carrier                  ) = 'PLC_A and PLC_B'       ! Description\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_shaft                    )                           ! $SVG_stage_01.$SVG_shaft\n");
    fprintf(new_ID, "      subvar($_diameter, str= '%e mm')                                                     ! $SVG_stage_01.$SVG_shaft.$_diameter\n");
    fprintf(new_ID, "      subvar($_length, str= '%e mm')                                                       ! $SVG_stage_01.$SVG_shaft.$_length\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_shaft                    )                           ! $SVG_stage_01.$SVG_shaft\n");
    fprintf(new_ID, "subvargroup.end (                   $SVG_stage_01                 )                           ! $SVG_stage_01\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_stage_02                 )                           ! $SVG_stage_02\n");
    fprintf(new_ID, "   subvar($_normal_module, str= '%e mm')                                                    ! $SVG_stage_02.$_normal_module\n");
    fprintf(new_ID, "   subvar($_face_width, str= '%e mm')                                                      ! $SVG_stage_02.$_face_width\n");
    fprintf(new_ID, "   subvar($_center_distance, str= '%e mm')                                                 ! $SVG_stage_02.$_center_distance\n");
    fprintf(new_ID, "   subvar($_pressure_angle, str= '20.0 deg')                                                  ! $SVG_stage_02.$_pressure_angle\n");
    fprintf(new_ID, "   subvar($_helix_angle, str= '0.0 deg')                                                      ! $SVG_stage_02.$_helix_angle\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_sun                      )                           ! $SVG_stage_02.$SVG_sun\n");
    fprintf(new_ID, "      subvar($_num_teeth, str= '18')                                                          ! $SVG_stage_02.$SVG_sun.$_num_teeth\n");
    fprintf(new_ID, "      subvar($_prof_shift_coeff, str= '0.389')                                                ! $SVG_stage_02.$SVG_sun.$_prof_shift_coeff\n");
    fprintf(new_ID, "      subvar($_diam_bore, str= '%e mm')                                                    ! $SVG_stage_02.$SVG_sun.$_diam_bore\n");
    fprintf(new_ID, "      subvar($_angle, str= '12*(180deg)/$SVG_stage_02.$SVG_sun.$_num_teeth')                  ! $SVG_stage_02.$SVG_sun.$_angle\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_sun                      )                           ! $SVG_stage_02.$SVG_sun\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_planet                   )                           ! $SVG_stage_02.$SVG_planet\n");
    fprintf(new_ID, "      subvar($_num_teeth, str= '36')                                                          ! $SVG_stage_02.$SVG_planet.$_num_teeth\n");
    fprintf(new_ID, "      subvar($_prof_shift_coeff, str= '0.504')                                                ! $SVG_stage_02.$SVG_planet.$_prof_shift_coeff\n");
    fprintf(new_ID, "      subvar($_diam_bore, str= '%e mm')                                                    ! $SVG_stage_02.$SVG_planet.$_diam_bore\n");
    fprintf(new_ID, "      subvar($_pin_width, str= '1.4*$SVG_stage_02.$_face_width')                              ! $SVG_stage_02.$SVG_planet.$_pin_width\n");
    fprintf(new_ID, "      subvar($_angle, str= '20*(180 deg)/$SVG_stage_02.$SVG_planet.$_num_teeth')              ! $SVG_stage_02.$SVG_planet.$_angle\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_A                        )                           ! $SVG_stage_02.$SVG_planet.$SVG_A\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_02.$SVG_carrier.$_width/2.0')                           ! $SVG_stage_02.$SVG_planet.$SVG_A.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_02.$SVG_planet.$SVG_A.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_02.$SVG_planet.$SVG_A.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '%e N/m')                                                      ! $SVG_stage_02.$SVG_planet.$SVG_A.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_02.$SVG_planet.$SVG_A.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '%e Nm/rad')                                                ! $SVG_stage_02.$SVG_planet.$SVG_A.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '%e Nm/rad')                                               ! $SVG_stage_02.$SVG_planet.$SVG_A.$_K_gamma\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_A                        )                           ! $SVG_stage_02.$SVG_planet.$SVG_A\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_planet                   )                           ! $SVG_stage_02.$SVG_planet\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_ring                     )                           ! $SVG_stage_02.$SVG_ring\n");
    fprintf(new_ID, "      subvar($_num_teeth, str= '93')                                                          ! $SVG_stage_02.$SVG_ring.$_num_teeth\n");
    fprintf(new_ID, "      subvar($_prof_shift_coeff, str= '0.117')                                                ! $SVG_stage_02.$SVG_ring.$_prof_shift_coeff\n");
    fprintf(new_ID, "      subvar($_diam_bore, str= '%e mm')                                                    ! $SVG_stage_02.$SVG_ring.$_diam_bore\n");
    fprintf(new_ID, "      subvar($_angle, str= '45.5*(180 deg)/$SVG_stage_02.$SVG_ring.$_num_teeth')              ! $SVG_stage_02.$SVG_ring.$_angle\n");
    fprintf(new_ID, "      subvar($_x, str= '$SVG_main_shaft.$_length + $SVG_stage_01.$SVG_carrier.$_width + $SVG_stage_01.$SVG_shaft.$_length + $SVG_stage_02.$SVG_carrier.$_width/2.0') ! $SVG_stage_02.$SVG_ring.$_x\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_ring                     )                           ! $SVG_stage_02.$SVG_ring\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_carrier                  )                           ! $SVG_stage_02.$SVG_carrier\n");
    fprintf(new_ID, "      subvar($_diameter_in, str= '1.4*$SVG_stage_02.$_center_distance	')                      ! $SVG_stage_02.$SVG_carrier.$_diameter_in\n");
    fprintf(new_ID, "      subvar($_diameter_out, str= '2.6*$SVG_stage_02.$_center_distance	')                     ! $SVG_stage_02.$SVG_carrier.$_diameter_out\n");
    fprintf(new_ID, "      subvar($_width, str= '1.2*$SVG_stage_02.$_face_width')                                  ! $SVG_stage_02.$SVG_carrier.$_width\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_A                        )                           ! $SVG_stage_02.$SVG_carrier.$SVG_A\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_main_shaft.$_length + $SVG_stage_01.$SVG_carrier.$_width + $SVG_stage_01.$SVG_shaft.$_length') ! $SVG_stage_02.$SVG_carrier.$SVG_A.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_02.$SVG_carrier.$SVG_A.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_02.$SVG_carrier.$SVG_A.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '%e N/m')                                                      ! $SVG_stage_02.$SVG_carrier.$SVG_A.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_02.$SVG_carrier.$SVG_A.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '%e Nm/rad')                                                ! $SVG_stage_02.$SVG_carrier.$SVG_A.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '$SVG_stage_02.$SVG_carrier.$SVG_A.$_K_beta')                 ! $SVG_stage_02.$SVG_carrier.$SVG_A.$_K_gamma\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_A                        )                           ! $SVG_stage_02.$SVG_carrier.$SVG_A\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_B                        )                           ! $SVG_stage_02.$SVG_carrier.$SVG_B\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_02.$SVG_carrier.$SVG_A.$_x + $SVG_stage_02.$SVG_carrier.$_width') ! $SVG_stage_02.$SVG_carrier.$SVG_B.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_02.$SVG_carrier.$SVG_B.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '$SVG_stage_02.$SVG_carrier.$SVG_A.$_K_y')                        ! $SVG_stage_02.$SVG_carrier.$SVG_B.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '$SVG_stage_02.$SVG_carrier.$SVG_A.$_K_z')                        ! $SVG_stage_02.$SVG_carrier.$SVG_B.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_02.$SVG_carrier.$SVG_B.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '$SVG_stage_02.$SVG_carrier.$SVG_A.$_K_beta')                  ! $SVG_stage_02.$SVG_carrier.$SVG_B.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '$SVG_stage_02.$SVG_carrier.$SVG_A.$_K_beta')                 ! $SVG_stage_02.$SVG_carrier.$SVG_B.$_K_gamma\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_B                        )                           ! $SVG_stage_02.$SVG_carrier.$SVG_B\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_carrier                  )                           ! $SVG_stage_02.$SVG_carrier\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_shaft                    )                           ! $SVG_stage_02.$SVG_shaft\n");
    fprintf(new_ID, "      subvar($_diameter, str= '%e mm')                                                     ! $SVG_stage_02.$SVG_shaft.$_diameter\n");
    fprintf(new_ID, "      subvar($_length, str= '%e mm')                                                       ! $SVG_stage_02.$SVG_shaft.$_length\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_shaft                    )                           ! $SVG_stage_02.$SVG_shaft\n");
    fprintf(new_ID, "subvargroup.end (                   $SVG_stage_02                 )                           ! $SVG_stage_02\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_stage_03                 )                           ! $SVG_stage_03\n");
    fprintf(new_ID, "   subvar($_normal_module, str= '%e mm')                                                    ! $SVG_stage_03.$_normal_module\n");
    fprintf(new_ID, "   subvar($_face_width, str= '%e mm')                                                      ! $SVG_stage_03.$_face_width\n");
    fprintf(new_ID, "   subvar($_center_distance, str= '%e mm')                                                 ! $SVG_stage_03.$_center_distance\n");
    fprintf(new_ID, "   subvar($_pressure_angle, str= '20.0 deg')                                                  ! $SVG_stage_03.$_pressure_angle\n");
    fprintf(new_ID, "   subvar($_helix_angle, str= '10.0 deg')                                                     ! $SVG_stage_03.$_helix_angle\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_pinion                   )                           ! $SVG_stage_03.$SVG_pinion\n");
    fprintf(new_ID, "      subvar($_num_teeth, str= '24')                                                          ! $SVG_stage_03.$SVG_pinion.$_num_teeth\n");
    fprintf(new_ID, "      subvar($_prof_shift_coeff, str= '0.480')                                                ! $SVG_stage_03.$SVG_pinion.$_prof_shift_coeff\n");
    fprintf(new_ID, "      subvar($_diam_bore, str= '%e mm')                                                    ! $SVG_stage_03.$SVG_pinion.$_diam_bore\n");
    fprintf(new_ID, "      subvar($_pin_width, str= '1.4*$SVG_stage_03.$_face_width')                              ! $SVG_stage_03.$SVG_pinion.$_pin_width\n");
    fprintf(new_ID, "      subvar($_angle, str= '12.5*(180.0 deg)/$SVG_stage_03.$SVG_pinion.$_num_teeth')          ! $SVG_stage_03.$SVG_pinion.$_angle\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_A                        )                           ! $SVG_stage_03.$SVG_pinion.$SVG_A\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_01.$SVG_carrier.$_width/2.0')                           ! $SVG_stage_03.$SVG_pinion.$SVG_A.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_pinion.$SVG_A.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_pinion.$SVG_A.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '$SVG_stage_03.$SVG_pinion.$SVG_A.$_K_y')                         ! $SVG_stage_03.$SVG_pinion.$SVG_A.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_03.$SVG_pinion.$SVG_A.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '%e Nm/rad')                                                ! $SVG_stage_03.$SVG_pinion.$SVG_A.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '%e Nm/rad')                                               ! $SVG_stage_03.$SVG_pinion.$SVG_A.$_K_gamma\n");
    fprintf(new_ID, "         subvar($_y, str= '-$SVG_stage_03.$_center_distance + $SVG_bed_plate.$_width/2.0')    ! $SVG_stage_03.$SVG_pinion.$SVG_A.$_y\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_A                        )                           ! $SVG_stage_03.$SVG_pinion.$SVG_A\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_B                        )                           ! $SVG_stage_03.$SVG_pinion.$SVG_B\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_01.$SVG_carrier.$_width/2.0')                           ! $SVG_stage_03.$SVG_pinion.$SVG_B.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_pinion.$SVG_B.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_pinion.$SVG_B.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_pinion.$SVG_B.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_03.$SVG_pinion.$SVG_B.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '$SVG_stage_03.$SVG_pinion.$SVG_A.$_K_beta')                   ! $SVG_stage_03.$SVG_pinion.$SVG_B.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '$SVG_stage_03.$SVG_pinion.$SVG_A.$_K_gamma')                 ! $SVG_stage_03.$SVG_pinion.$SVG_B.$_K_gamma\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_B                        )                           ! $SVG_stage_03.$SVG_pinion.$SVG_B\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_C                        )                           ! $SVG_stage_03.$SVG_pinion.$SVG_C\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_01.$SVG_carrier.$_width/2.0')                           ! $SVG_stage_03.$SVG_pinion.$SVG_C.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_pinion.$SVG_C.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_pinion.$SVG_C.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_pinion.$SVG_C.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_03.$SVG_pinion.$SVG_C.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '$SVG_stage_03.$SVG_pinion.$SVG_A.$_K_beta')                   ! $SVG_stage_03.$SVG_pinion.$SVG_C.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '$SVG_stage_03.$SVG_pinion.$SVG_A.$_K_gamma')                 ! $SVG_stage_03.$SVG_pinion.$SVG_C.$_K_gamma\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_C                        )                           ! $SVG_stage_03.$SVG_pinion.$SVG_C\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_pinion                   )                           ! $SVG_stage_03.$SVG_pinion\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_wheel                    )                           ! $SVG_stage_03.$SVG_wheel\n");
    fprintf(new_ID, "      subvar($_num_teeth, str= '95')                                                          ! $SVG_stage_03.$SVG_wheel.$_num_teeth\n");
    fprintf(new_ID, "      subvar($_prof_shift_coeff, str= '0.669')                                                ! $SVG_stage_03.$SVG_wheel.$_prof_shift_coeff\n");
    fprintf(new_ID, "      subvar($_diam_bore, str= '%e mm')                                                    ! $SVG_stage_03.$SVG_wheel.$_diam_bore\n");
    fprintf(new_ID, "      subvar($_pin_width, str= '1.4*$SVG_stage_03.$_face_width')                              ! $SVG_stage_03.$SVG_wheel.$_pin_width\n");
    fprintf(new_ID, "      subvar($_angle, str= '51*(180 deg)/$SVG_stage_03.$SVG_wheel.$_num_teeth')               ! $SVG_stage_03.$SVG_wheel.$_angle\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_A                        )                           ! $SVG_stage_03.$SVG_wheel.$SVG_A\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_03.$SVG_wheel.$_pin_width/2.0')                         ! $SVG_stage_03.$SVG_wheel.$SVG_A.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '0.0 N/m')                                                        ! $SVG_stage_03.$SVG_wheel.$SVG_A.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_wheel.$SVG_A.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_wheel.$SVG_A.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_03.$SVG_wheel.$SVG_A.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '%e Nm/rad')                                                ! $SVG_stage_03.$SVG_wheel.$SVG_A.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '$SVG_stage_03.$SVG_wheel.$SVG_A.$_K_beta')                   ! $SVG_stage_03.$SVG_wheel.$SVG_A.$_K_gamma\n");
    fprintf(new_ID, "         subvar($_x_GB, str= '$SVG_stage_02.$SVG_carrier.$SVG_B.$_x + $SVG_stage_02.$SVG_shaft.$_length') ! $SVG_stage_03.$SVG_wheel.$SVG_A.$_x_GB\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_A                        )                           ! $SVG_stage_03.$SVG_wheel.$SVG_A\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_B                        )                           ! $SVG_stage_03.$SVG_wheel.$SVG_B\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_03.$SVG_wheel.$SVG_A.$_x*6.0/7.0')                      ! $SVG_stage_03.$SVG_wheel.$SVG_B.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_wheel.$SVG_B.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_wheel.$SVG_B.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '$SVG_stage_03.$SVG_wheel.$SVG_B.$_K_y')                          ! $SVG_stage_03.$SVG_wheel.$SVG_B.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_03.$SVG_wheel.$SVG_B.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '%e Nm/rad')                                                ! $SVG_stage_03.$SVG_wheel.$SVG_B.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '%e Nm/rad')                                               ! $SVG_stage_03.$SVG_wheel.$SVG_B.$_K_gamma\n");
    fprintf(new_ID, "         subvar($_x_GB, str= '$SVG_stage_03.$SVG_wheel.$SVG_A.$_x_GB + $SVG_stage_03.$SVG_wheel.$SVG_A.$_x + $SVG_stage_03.$SVG_wheel.$SVG_B.$_x') ! $SVG_stage_03.$SVG_wheel.$SVG_B.$_x_GB\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_B                        )                           ! $SVG_stage_03.$SVG_wheel.$SVG_B\n");
    fprintf(new_ID, "      subvargroup.begin (           $SVG_C                        )                           ! $SVG_stage_03.$SVG_wheel.$SVG_C\n");
    fprintf(new_ID, "         subvar($_x, str= '$SVG_stage_03.$SVG_wheel.$SVG_A.$_x*6.0/7.0')                      ! $SVG_stage_03.$SVG_wheel.$SVG_C.$_x\n");
    fprintf(new_ID, "         subvar($_K_x, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_wheel.$SVG_C.$_K_x\n");
    fprintf(new_ID, "         subvar($_K_y, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_wheel.$SVG_C.$_K_y\n");
    fprintf(new_ID, "         subvar($_K_z, str= '%e N/m')                                                      ! $SVG_stage_03.$SVG_wheel.$SVG_C.$_K_z\n");
    fprintf(new_ID, "         subvar($_K_alpha, str= '0.0 Nm/rad')                                                 ! $SVG_stage_03.$SVG_wheel.$SVG_C.$_K_alpha\n");
    fprintf(new_ID, "         subvar($_K_beta, str= '%e Nm/rad')                                                ! $SVG_stage_03.$SVG_wheel.$SVG_C.$_K_beta\n");
    fprintf(new_ID, "         subvar($_K_gamma, str= '%e Nm/rad')                                               ! $SVG_stage_03.$SVG_wheel.$SVG_C.$_K_gamma\n");
    fprintf(new_ID, "         subvar($_x_GB, str= '$SVG_stage_03.$SVG_wheel.$SVG_A.$_x_GB + $SVG_stage_03.$SVG_wheel.$_pin_width') ! $SVG_stage_03.$SVG_wheel.$SVG_C.$_x_GB\n");
    fprintf(new_ID, "      subvargroup.end (             $SVG_C                        )                           ! $SVG_stage_03.$SVG_wheel.$SVG_C\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_wheel                    )                           ! $SVG_stage_03.$SVG_wheel\n");
    fprintf(new_ID, "   subvargroup.begin (              $SVG_shaft                    )                           ! $SVG_stage_03.$SVG_shaft\n");
    fprintf(new_ID, "      subvar($_diameter, str= '%e mm')                                                     ! $SVG_stage_03.$SVG_shaft.$_diameter\n");
    fprintf(new_ID, "      subvar($_length, str= '%e mm')                                                      ! $SVG_stage_03.$SVG_shaft.$_length\n");
    fprintf(new_ID, "   subvargroup.end (                $SVG_shaft                    )                           ! $SVG_stage_03.$SVG_shaft\n");
    fprintf(new_ID, "subvargroup.end (                   $SVG_stage_03                 )                           ! $SVG_stage_03\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "subvargroup.begin (                 $SVG_bearing_damping          )                           ! $SVG_bearing_damping\n");
    fprintf(new_ID, "   subvar($_D_x, str= '%e N/(m/s)')                                                        ! $SVG_bearing_damping.$_D_x\n");
    fprintf(new_ID, "   subvar($_D_y, str= '%e N/(m/s)')                                                        ! $SVG_bearing_damping.$_D_y\n");
    fprintf(new_ID, "   subvar($_D_z, str= '%e N/(m/s)')                                                       ! $SVG_bearing_damping.$_D_z\n");
    fprintf(new_ID, "   subvar($_D_alpha, str= '0.0 Nm/(rad/s)')                                                   ! $SVG_bearing_damping.$_D_alpha\n");
    fprintf(new_ID, "   subvar($_D_beta, str= '%e Nm/(rad/s)')                                                   ! $SVG_bearing_damping.$_D_beta\n");
    fprintf(new_ID, "   subvar($_D_gamma, str= '%e Nm/(rad/s)')                                                  ! $SVG_bearing_damping.$_D_gamma\n");
    fprintf(new_ID, "subvargroup.end (                   $SVG_bearing_damping          )                           ! $SVG_bearing_damping\n");
    fprintf(new_ID, "\n");
    fprintf(new_ID, "\n");
end
